version: "3"
services:
  mongoservice:
    image: mongo
    volumes:
      - $GOPATH/src/Spec-Center/volume:/data/db
    ports:
      - "27018:27017"
  spec-center:
    build: .
    depends_on:
      - mongoservice
    ports:
      - "8080:8080"
volumes:
  volume: